# Generated by Django 5.1.3 on 2024-12-04 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_alter_task_context_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='context',
            field=models.TextField(max_length=120),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=30),
        ),
    ]
