# Generated by Django 5.1.3 on 2024-12-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0003_alter_task_context_alter_task_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='context',
            field=models.TextField(max_length=80),
        ),
    ]
