# Generated by Django 5.1.3 on 2024-12-06 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0004_alter_task_context'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='context',
            field=models.TextField(max_length=120),
        ),
    ]
